{% set version = "0.10.1" %}

package:
  name: ansible-bender
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/ansible-bender/ansible-bender-{{ version }}.tar.gz
  sha256: 2b2786e870106e22e17123b8cd6fa900ee7a72f6fbefbf8bd57aaee909c95089

build:
  number: 0
  noarch: python
  entry_points:
    - ansible-bender = ansible_bender.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.6
    - jsonschema
    - pyyaml
    - tabulate
    - ansible

test:
  imports:
    - ansible_bender
  commands:
    - pip check
    - ansible-bender --help
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-bender
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool which builds container images using Ansible playbooks
  doc_url: https://ansible-community.github.io/ansible-bender/build/html/index.html
  dev_url: https://github.com/ansible-community/ansible-bender

extra:
  recipe-maintainers:
    - lsetiawan
